### ISSUE TITLE
[v3] Generated code points to obsolete documentation

### ISSUE THREAD

**Issue by huysamen** [goadesign/goa.design#108]
The generated `v3` code in `cmd/svc/http.go` says to check `goa.design/encoding` for reference, however it no longer exists.

**Comment by raphael** [comment]
Thank you for the report, we probably should add back a page that explains encoding and decoding. Will be working on it.

**Comment by raphael** [comment]
Added a [new page](https://goa.design/implement/encoding/) explaining encoding and decoding in v2/v3, thank you! 

cc @ikawaha @tchssk
