### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by saniales** [goadesign/goa.design#114]
I am going to take care of the italian translation of the website

**Comment by raphael** [comment]
This is great! Thank you.

**Comment by saniales** [comment]
Can i avoid to translate the Blog section in the first PR? I think the unique source of truth for blog section should be english language @raphael

**Comment by raphael** [comment]
Yes agree, it wasn't translated in Japanese either.

**Comment by saniales** [comment]
Check the PR @raphael
