### ISSUE TITLE
Missing page "Working with Data Types"

### ISSUE THREAD

**Issue by mpaquette1** [goadesign/goa.design#37]
My data structures require int64 fields, but using Goa's "Integer" type in the design.go file means everything is getting dumbed down to an int.  

In trying to find a way around this, I searched the goa docs and clicked on the topic "Working with Data Types" which leads to a 404 error.

**Comment by raphael** [comment]
Thanks for the report! where was the broken link? the link in the menu seems to work ok for me.

**Comment by raphael** [comment]
BTW generating int64 is not supported atm, there's an issue opened for it and it's something that will get added in the future.

**Comment by mpaquette1** [comment]
Thanks for the quick reply.  On the page http://goa.design/reference/goa/design/apidsl/, I typed "data types" in the search box at the top.  A list of matches appears, the first one being "Working with Data Types" which links to http://goa.design/design/types.html, which gives an "Oh Noes! Something is amiss..." message.

**Comment by mpaquette1** [comment]
Also, thanks for pointing out that the link in the menu works fine.  I should have tried that one first.

**Comment by raphael** [comment]
I was able to repro thanks! looks like the index is outdated for some reason, will look into it.

**Comment by raphael** [comment]
this is now fixed.
