### ISSUE TITLE
Got error generate gorma/design

### ISSUE THREAD

**Issue by ak2003** [goadesign/goa.design#89]
When i run

$ goagen --design=gorma/design gen --pkg-path=gorma/design

I got

../github.com/goadesign/gorma/relationalmodel.go:9:2: cannot find package "bitbucket.org/pkg/inflect" in any of:
        /usr/local/go/src/bitbucket.org/pkg/inflect (from $GOROOT)

Do you have solution?

**Comment by raphael** [comment]
Sounds like you are missing some dependencies. Try doing:
```
go get -u -v github.com/goadesign/gorma/...
```
